### ISSUE TITLE
Wrong NFT delivered during transfer using the Web Wallet UI (Video)

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#538] opened 2022-06-06 18:34 UTC
We've seen a few incidents where the wrong NFT has been sent on Loopring.io

When does this happen?
1) users cycle thru their many NFT pages while not waiting for the images to load 
2) then continuing click on the 'next'/'previous' page 
3) click 'transfer'

Please watch video (start at 1:30) - https://github.com/Loopring/loopring-wallet-feedback/issues/199#issuecomment-1124454094

We believe this is only a web app issue
"Mobile app doesn't seem to have the issues, so my guess is something to do with how meta is loaded and from what source mixed with an abundance of, or maybe lack of, async stuff in React."  - sk33z3r.eth

**Comment by windatang** [comment] 2022-06-11 16:31
fixed please test

**Comment by sk33z3r** [comment] 2022-06-12 17:26
I've been testing this today. The original behavior described in https://github.com/Loopring/loopring-wallet-feedback/issues/199 appears to be a lot smoother now. There's a slight delay when I change pages before I am able to click the next arrow, and the time it takes to load the images/metadata seems faster.

I'm going to run a few more transfer tests, though.

I do want to note that data still leaks somewhere, as this bug still occurs:
https://github.com/Loopring/loopring-wallet-feedback/issues/201

**Comment by sk33z3r** [comment] 2022-06-13 01:26
I can't reproduce as easily as I was able to before.

In my main wallet I did one where I clicked as quickly as I could through 30 pages, chose an NFT, and then transferred.

I did another by clicking through only 10 pages, and even finished the transfer before all the images and meta loaded.

All cases sent the correct NFT, and load times in general are greatly improved.

**Closed** 2022-06-14 07:13 UTC
